version: "3"
services:
  backend:
    build:
      context: ./
    image: staff-schedule:latest
    container_name: staff-schedule
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - staff-schedule-net
    depends_on:
      - mysqldb

  mysqldb:
    image: 'mysql:5.7'
    container_name: staff-schedule-db
    ports:
      - "3307:3306"
    networks:
      - staff-schedule-net
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=staff-schedule-db
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=P@ssw0rd
networks:
  staff-schedule-net:
